### PR TITLE
Basic autonomous with a ton of bloat

### PR DESCRIPTION
**Pull request by eandr127**
This is mostly ported from last year, so the controls will need to be ported for the robot

### CODE REVIEW

**Comment by eandr127** [comment]
I will redo this from my fork and rename the packages for the team2706.ca domain

**Comment by ounsworth** [comment]
Nice! Thanks for moving your code over Ryan!

**Comment by eandr127** [comment]
Thanks.  Would you be able to add this repository to the Autonomous team?

**Comment by ounsworth** [comment]
Done!

**Comment by ounsworth** [comment]
I also made sure you have admin rights for both the Autonomous team, and the 2706-Autonomous repo.

**Comment by eandr127** [comment]
Okay, thank you.

**Pull request closed without merging**
